name: Python Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Project
      run: python ./Proyecto/main.py
    - name: Install Dependencies
      run: python -m pip install --upgrade pip
    - name: Run Test
      run: cd ./Proyecto/tester && python -m unittest discover -s -p 'tester.py'