name: Python Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: python -m pip install --upgrade pip && python -m pip install pynput && python -m pip install numpy && python -m pip install colorama
    - name: Install PyKE
      run: wget https://sourceforge.net/projects/pyke/files/pyke/1.1.1/pyke3-1.1.1.zip && unzip pyke3-1.1.1.zip && cd pyke-1.1.1 && python setup.py build && python setup.py install
    - name: Run Project
      run: cd Proyecto && python main.py
    - name: Run Test
      run: |
        cd ./Proyecto/tester
        python test1.py
        python test2.py
        python test3.py
        python test4.py
        python test5.py
        python test6.py
        python test7.py
        python test8.py
        python test9.py
        python test10.py
        python test11.py
        python test12.py
        python test13.py
        python test14.py
        python test15.py
        python test16.py
        python test17.py
        python test18.py