name: Python Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: python -m pip install --upgrade pip && python -m pip install pynput && python -m pip install numpy
    - name: Install PyKE
      run: wget https://sourceforge.net/projects/pyke/files/pyke/1.1.1/pyke3-1.1.1.zip && unzip pyke3-1.1.1.zip && cd pyke-1.1.1 && python setup.py build && python setup.py install
    - name: Run Project
      run: python ./Proyecto/main.py
    - name: Run Test
      run: cd ./Proyecto/tester && python -m unittest 'test_tokenizer.py'
